version: 2
updates:
  # Python dependencies for model
  - package-ecosystem: "pip"
    directory: "/model"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  # Python dependencies for service
  - package-ecosystem: "pip"
    directory: "/service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      docker-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
