name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build Docker image
      working-directory: ./service
      run: docker build -t image-similarity-service:${{ github.sha }} .
